#!/bin/bash

#PathSocket="/tmp/swiftpoint.x1.profileswitch"
PathSocket="/tmp/swiftpoint.x1.v2.command"

if [ ! -e "$PathSocket" ]; then
	echo "Socket not found: $PathSocket"
	exit 1
fi

echo -n "$@" | socat - UNIX-CONNECT:"$PathSocket",shut-none
